query:
  ingress:
    enabled: true

    annotations: {}
    ingressClassName: webapprouting.kubernetes.azure.com

    hosts: 
      - "jaeger.k8s-tests2.tst"
    pathType: Prefix

# Allow recieving traces from Istio
collector:
  service:
    zipkin: 
      port: 9411


cassandra:
  persistence:
    # To enable persistence, please see the documentation for the Cassandra chart
    enabled: true
    storageClass: default
    size: 5Gi
  config:
    cluster_size: 1
  livenessProbe:
    initialDelaySeconds: 180
    periodSeconds: 60
    timeoutSeconds: 10
    # successThreshold: 1
    # failureThreshold: 3
  readinessProbe:
    initialDelaySeconds: 180
    periodSeconds: 60
    timeoutSeconds: 10
    # successThreshold: 1
    # failureThreshold: 3
    # address: "${POD_IP}"
