environment: prod

redis_host: automation-andrei-prod.redis.cache.windows.net

deployment:
  image:
    tag: 2
  replicas: 1
    
secret:
  redis_pass: AgCxEtxDJA0A4jL9QgEKvtpQ9arrI2bWs3lje4eItSUtI00rJYfPKU8thLuPhyrYwqkObcMZO0qpY3lNJLfWaJLscE1yWI0kLpxCVmoDez81hHdi5PPrmgU7LLXdkb2Bst7+63cHaSCqesmuDjkn8k1LbUwUMenSwoL5sKwdXV8wg4aA3yKRnRMW7QthEYksBkj23ZGgQWPZ3SwyrU9zibI0OxhAxA6/Pm02SqbdWqJNNVvkGGJ6YHlt2kKW/XOO7erxAI+vYuJQg9l+wU+lDrEuFJpG0G2toh4BCn5a8RJfE4kOkJ6XZk7XTKjP6dzh2dZYrne0AIXQinXNm0Jg5XMrAMn1eUfH+ZLwB3JPAIxNDj2ht6b1xhmLFqhHIxTIXUUznmXx3KM/gLuSCVQoiOr1turIt8TnRp5bddF+46nfRhwHGB8ZM42iAmYJbyPxY6ljBiIdWvp9h5P4FApBM42O+y+V5greoFDjz8/r98onmy3UXH7u1eZrr3KQDpJVAeAhHT5/bBxlcsdOr/ulvhThaOnRqsAGKKXskwh6f/ypJjssuSBxwIVazST8erZwAmEGn+KNTfkt90hEM818ZluZtwg9MQoqoQvvZobXsnFev8RvWZFkv6nlbr4Vko/fyUn6FrN7xha8jZX7xa44WbmS7hQNIUiFN0mnBVsUhaPi7piCXBoWv6GEPKNTnaJRzxZvrjbrh6Um3rnKWW6QcBN1UH5AKaZh2me3y/+EB8fE/fBBNyALquf7Q2OMFQ== # This value was modified by the sealed-secrets pipeline
