environment: dev
    
redis_host: automation-andrei-dev.redis.cache.windows.net

deployment:
  image:  
    tag: 2
  replicas: 1

secret:
  redis_pass: AgC84cCfCSImZH6sjL+VgptJsR4QyWLSMeXJamhnQRUVQrm7qmnq0lcpNr74vJ4LlMR47RrZQW1gUvTqzEDOF394v88kHODLcyUiWAlAXWwtBCf3vIT/qwAJW60twkhXmfU7NB3iaUBYXQmlyroMDBCUkMWCILzwUVI7E3uI5YWucGgolYrmHIna2K11eA5AzQPkfrYAuuo5XOTIERU98jiuvd5c8Jcp8DWsNMp+L22Yjpy2X+fKPgKAqTvfTUSva5lxwIcFPtB+Y8OOmI2X9ONGlG8FKxgi7mmmD7DA72KZW77hw1nFjX0yrgKScg687CVzg+ZsKhrftCLklvLKY0QMRNzP++iPgVu/D+coQs0zJxg/GCPIs0W/R0Jw/e2Rp8WbpV4QdzuKFjKok5WqsWm+oXW5PAncDZgqrphzyD/SuJ4wS0WICP40tgvp84+EaxovL7ExR79Z75cUULDPxaiaEtroivyHgRv7WttWyLVmYVR0bsdRbyAFnB+wivB+jG41fHb/dr9btTtC62l64Wvh0RkdkiPROINozgLKcSJh7mSNPcHFJlq15IdO8ZiSjsvtSmbgh+cQiQyoYgJkp7yd4fOhdW8EScY+5CQ6wZAQQVzct4h+pq6Mhj7y4yWKZuo0FVqbA4bHdfFWQ1ObBwjV7SoLMTTswgmlLdOpmtN9pq86+22QROD5FGwqosLFnF6p/IHqzQ7t/GDV7kX/Cegw471rQS3BNLx9xmX8+scvtPpb0iBCPNGseqN7Fg== # This value was modified by the sealed-secrets pipeline
